# -*- coding: utf-8 -*-
"""Soal3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aXLEMOEnzkOhebhRac4I8_N0sD7hc9JQ
"""

jumlah_baris = int(input("Masukkan jumlah baris: "))


for i in range(1, jumlah_baris + 1):
    print("*" * i)