# -*- coding: utf-8 -*-
"""Soal2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aANJXrHZ2tHHVdaJc0psVq6jL0ydsBog
"""

x = 0
for i in range(1, 20, 2):
  x = x + i
print(x)